language: node_js
node_js:
  - "node"
dist: trusty
sudo: false
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true
install:
  - yarn
script:
  - yarnpkg build
deploy:
  provider: surge
  project: ./build/
  domain: thoriumsim.com
  skip_cleanup: true

